[package]
name = "grb-sys"
version = "0.5.0"
edition = "2018"
build = "build.rs"
license = "MIP"
description = "Gurobi C API FFI declarations."
homepage = "https://github.com/ykrist/rust-grb/"
repository = "https://github.com/ykrist/rust-grb/"
